# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Roy <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: terminal 0.2.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-02-20 14:37+0800\n"
"PO-Revision-Date: 2021-02-20 14:40+0800\n"
"Last-Translator: Roy <EMAIL@ADDRESS>\n"
"Language-Team: en <wecube>\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: terminal/apps/assets/api.py:43
#, python-format
msgid "Not allowed to perform %(action)s on Asset(#%(id)s)"
msgstr ""

#: terminal/apps/assets/api.py:81 terminal/apps/assets/api.py:151
#, python-format
msgid "%(expression)s not acceptable, expect url?expression=value"
msgstr ""

#: terminal/apps/assets/api.py:89 terminal/apps/assets/api.py:159
#, python-format
msgid "%(expression)s invalid"
msgstr ""

#: terminal/apps/assets/api.py:216 terminal/apps/assets/api.py:256
#, python-format
msgid "%(filepath)s not exist"
msgstr ""

#: terminal/apps/assets/api.py:223
#, python-format
msgid "upload to %(filepath)s error: permission denied"
msgstr ""

#: terminal/apps/assets/api.py:263
#, python-format
msgid "download %(filepath)s error: permission denied"
msgstr ""

#: terminal/apps/assets/api.py:264
#, python-format
msgid "%(filepath)s is not a regular file"
msgstr ""

#: terminal/apps/assets/api.py:274
#, python-format
msgid "file size (%(size)s bytes) exceeds maximum of %(maximum_size)s"
msgstr ""

#: terminal/apps/assets/api.py:456 terminal/apps/assets/api.py:477
msgid "length of roles.owner must be >= 1"
msgstr ""

#: terminal/apps/assets/api.py:509 terminal/apps/assets/api.py:522
#, python-format
msgid "the resource(%(resource)s) does not belong to you"
msgstr ""

#: terminal/apps/assets/controller.py:64 terminal/apps/assets/controller.py:81
#, python-format
msgid "missing query: %(name)s"
msgstr ""

#: terminal/apps/assets/controller.py:67
#, python-format
msgid "form-data named \"%(name)s\" not found"
msgstr ""

#: terminal/common/controller.py:44 terminal/common/controller.py:62
#: terminal/common/controller.py:91
msgid "data must be list type"
msgstr ""

#: terminal/common/controller.py:124
msgid "data must be dict type"
msgstr ""

#: terminal/common/exceptions.py:30
msgid "Plugin Business Processing Error"
msgstr ""

#: terminal/common/exceptions.py:40
msgid "Field Missing"
msgstr ""

#: terminal/common/exceptions.py:44
#, python-format
msgid "column: %(attribute)s must be specific"
msgstr ""

#: terminal/common/exceptions.py:54
msgid "Validation Error"
msgstr ""

#: terminal/common/exceptions.py:58
#, python-format
msgid "column %(attribute)s validate failed, because: %(msg)s"
msgstr ""

#: terminal/common/exceptions.py:74 terminal/common/wshandler.py:162
#, python-format
msgid "the resource(%(resource)s) you request not found"
msgstr ""

#: terminal/common/exceptions.py:84
msgid "Batch Operation Partial Error"
msgstr ""

#: terminal/common/exceptions.py:88
#, python-format
msgid "fail to %(action)s [%(num)s] record, detail error in the data block"
msgstr ""

#: terminal/common/exceptions.py:98
msgid "Conflict"
msgstr ""

#: terminal/common/exceptions.py:102
#, python-format
msgid "object[%(oid)s] is used by %(name)s"
msgstr ""

#: terminal/common/s3.py:40
msgid ""
"invalid s3 endpoint url, eg: [(http|https|s3)://]host[:port][/bucket/"
"object_key]"
msgstr ""

#: terminal/common/s3.py:65 terminal/common/s3.py:90
#, python-format
msgid "failed to download file[%(filepath)s] from s3: %(reason)s"
msgstr ""

#: terminal/common/ssh.py:65
#, python-format
msgid ""
"failed to authenticate %(username)s@%(host)s:%(port)s with password: "
"%(password)s, detail: %(detail)s"
msgstr ""

#: terminal/common/ssh.py:76
#, python-format
msgid ""
"failed to connect %(username)s@%(host)s:%(port)s with password: "
"%(password)s, detail: %(detail)s"
msgstr ""

#: terminal/common/ssh.py:85 terminal/common/ssh.py:121
#, python-format
msgid "failed to establish connection on %(host)s:%(port)s"
msgstr ""

#: terminal/common/ssh.py:104
#, python-format
msgid ""
"failed to authenticate %(username)s@%(host)s:%(port)s with private key, "
"detail: %(detail)s"
msgstr ""

#: terminal/common/ssh.py:113
#, python-format
msgid ""
"failed to connect %(username)s@%(host)s:%(port)s with private key, detail: "
"%(detail)s"
msgstr ""

#: terminal/common/utils.py:96
msgid "Connection Error"
msgstr ""

#: terminal/common/utils.py:97
msgid "Failed to establish a new connection"
msgstr ""

#: terminal/common/utils.py:103
msgid "Timeout Error"
msgstr ""

#: terminal/common/utils.py:104
msgid "Server do not respond"
msgstr ""

#: terminal/common/utils.py:113
msgid "Not Found"
msgstr ""

#: terminal/common/utils.py:114
msgid "The resource you request not exist"
msgstr ""

#: terminal/common/utils.py:128
msgid "Server Error"
msgstr ""

#: terminal/common/wshandler.py:152
msgid "missing param: asset_id"
msgstr ""

#: terminal/common/wshandler.py:157
msgid "invalid token"
msgstr ""

#: terminal/common/wshandler.py:245
#, python-format
msgid "error calling itsdangerous: %(reason)s"
msgstr ""

#: terminal/common/wshandler.py:273
#, python-format
msgid "cannot open directory \"%(name)s\": File not found"
msgstr ""

#: terminal/common/wshandler.py:281
#, python-format
msgid "cannot open directory \"%(name)s\": Permission denied"
msgstr ""

#: terminal/db/validator.py:17
#, python-format
msgid "expected string, not %(type)s "
msgstr ""

#: terminal/db/validator.py:20
#, python-format
msgid "length required: %(min)d <= %(value)d <= %(max)d"
msgstr ""

#: terminal/db/validator.py:33
#, python-format
msgid "reference of %(resource)s(%(id)s) not found"
msgstr ""

#: terminal/db/validator.py:45
#, python-format
msgid "expected %(choices)s, not %(value)s"
msgstr ""

#: terminal/db/validator.py:48
#, python-format
msgid "value should be >= 1, not %(value)s"
msgstr ""

#: terminal/db/validator.py:50
#, python-format
msgid "expected string in %(choices)s or int(>=1), not %(type)s "
msgstr ""
